CREATE TABLE ROLES_USUARIO (
    IDROLUSUARIO NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL,
    ESTADO NUMBER(1) NOT NULL CHECK (ESTADO IN (0, 1))
);

CREATE TABLE MODULOS_ACCESO (
    IDMODULOACCESO NUMBER NOT NULL,
    IDROLUSUARIO NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL,
    ESTADO NUMBER(1) NOT NULL CHECK (ESTADO IN (0, 1))
);

CREATE TABLE TIPOS_DOCUMENTO (
    IDTIPODOCUMENTO NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE USUARIOS (
    IDUSUARIO NUMBER NOT NULL,
    IDTIPODOCUMENTO NUMBER NOT NULL,
    IDROLUSUARIO NUMBER NOT NULL,
    PRIMERNOMBRE VARCHAR2(15) NOT NULL,
    SEGUNDONOMBRE VARCHAR2(15),
    PRIMERAPELLIDO VARCHAR2(15) NOT NULL,
    SEGUNDOAPELLIDO VARCHAR2(15),
    NUMERODOCUMENTO VARCHAR2(15) NOT NULL,
    CORREOELECTRONICO VARCHAR2(50),
    TELEFONO VARCHAR2(10),
    CELULAR VARCHAR2(10),
    NOMBREUSUARIO VARCHAR2(50) NOT NULL,
    CONTRASENA VARCHAR(255) NOT NULL,
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL,
    ESTADO NUMBER(1) NOT NULL CHECK (ESTADO IN (0, 1))
);

CREATE TABLE CLIENTES (
    IDCLIENTE NUMBER NOT NULL,
    IDTIPODOCUMENTO NUMBER NOT NULL,
    PRIMERNOMBRE VARCHAR2(15) NOT NULL,
    SEGUNDONOMBRE VARCHAR2(15),
    PRIMERAPELLIDO VARCHAR2(15) NOT NULL,
    SEGUNDOAPELLIDO VARCHAR2(15),
    NUMERODOCUMENTO VARCHAR2(15) NOT NULL,
    CORREOELECTRONICO VARCHAR2(50),
    TELEFONO VARCHAR2(10),
    CELULAR VARCHAR2(10),
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL,
    ESTADO NUMBER(1) NOT NULL CHECK (ESTADO IN (0, 1))
);

CREATE TABLE PROVEEDORES (
    IDPROVEEDOR NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    NUMERODOCUMENTO VARCHAR2(15) NOT NULL,
    CORREOELECTRONICO VARCHAR2(50),
    TELEFONO VARCHAR2(10),
    CELULAR VARCHAR2(10),
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL,
    ESTADO NUMBER(1) NOT NULL CHECK (ESTADO IN (0, 1))
);

CREATE TABLE CATEGORIAS_PRODUCTO (
    IDCATEGORIAPRODUCTO NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL,
    ESTADO NUMBER(1) NOT NULL CHECK (ESTADO IN (0, 1))
);

CREATE TABLE MARCAS (
    IDMARCA NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL,
    ESTADO NUMBER(1) NOT NULL CHECK (ESTADO IN (0, 1))
);

CREATE TABLE PRODUCTOS (
    IDPRODUCTO NUMBER NOT NULL,
    IDCATEGORIAPRODUCTO NUMBER NOT NULL,
    IDMARCA NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    PRECIOCOMPRA NUMBER(10, 2) NOT NULL,
    PRECIOVENTA NUMBER(10, 2) NOT NULL,
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL,
    ESTADO NUMBER(1) NOT NULL CHECK (ESTADO IN (0, 1))
);

CREATE TABLE FACTURAS_MAESTRAS (
    IDFACTURAMAESTRA NUMBER NOT NULL,
    IDUSUARIO NUMBER NOT NULL,
    IDCLIENTE NUMBER NOT NULL,
    MONTOPAGADO NUMBER(10, 2) NOT NULL,
    MONTOCAMBIO NUMBER(10, 2) NOT NULL,
    MONTOTOTAL NUMBER(10, 2) NOT NULL,
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE DETALLES_FACTURA (
    IDDETALLEFACTURA NUMBER NOT NULL,
    IDFACTURAMAESTRA NUMBER NOT NULL,
    IDPRODUCTO NUMBER NOT NULL,
    PRECIOVENTA NUMBER(10, 2) NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    MONTOTOTAL NUMBER(10, 2) NOT NULL
);

CREATE TABLE SUMINISTROS_MAESTROS (
    IDSUMINISTROMAESTRO NUMBER NOT NULL,
    IDUSUARIO NUMBER NOT NULL,
    IDPROVEEDOR NUMBER NOT NULL,
    MONTOTOTAL NUMBER(10, 2) NOT NULL,
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE DETALLES_SUMINISTRO (
    IDDETALLESUMINISTRO NUMBER NOT NULL,
    IDSUMINISTROMAESTRO NUMBER NOT NULL,
    PRECIOCOMPRA NUMBER(10, 2) NOT NULL,
    PRECIOVENTA NUMBER(10, 2) NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    MONTOTOTAL NUMBER(10, 2) NOT NULL,
    IDPRODUCTO INT NOT NULL
);

-- Llaves primarias para la tabla MODULOS_ACCESO
ALTER TABLE MODULOS_ACCESO ADD CONSTRAINT PK_MODULOSACCESO PRIMARY KEY (IDMODULOACCESO);

-- Llaves primarias para la tabla ROLES_USUARIO
ALTER TABLE ROLES_USUARIO ADD CONSTRAINT PK_ROLESUSUARIO PRIMARY KEY (IDROLUSUARIO);

-- Llaves primarias para la tabla TIPOS_DOCUMENTO
ALTER TABLE TIPOS_DOCUMENTO ADD CONSTRAINT PK_TIPOSDOCUMENTO PRIMARY KEY (IDTIPODOCUMENTO);

-- Llaves primarias para la tabla USUARIOS
ALTER TABLE USUARIOS ADD CONSTRAINT PK_USUARIOS PRIMARY KEY (IDUSUARIO);

-- Llaves primarias para la tabla CLIENTES
ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY (IDCLIENTE);

-- Llaves primarias para la tabla PROVEEDORES
ALTER TABLE PROVEEDORES ADD CONSTRAINT PK_PROVEEDORES PRIMARY KEY (IDPROVEEDOR);

-- Llaves primarias para la tabla CATEGORIAS_PRODUCTO
ALTER TABLE CATEGORIAS_PRODUCTO ADD CONSTRAINT PK_CATEGORIAPRODUCTO PRIMARY KEY (IDCATEGORIAPRODUCTO);

-- Llaves primarias para la tabla PRODUCTOS
ALTER TABLE PRODUCTOS ADD CONSTRAINT PK_PRODUCTOS PRIMARY KEY (IDPRODUCTO);

-- Llaves primarias para la tabla MARCAS
ALTER TABLE MARCAS ADD CONSTRAINT PK_MARCAS PRIMARY KEY (IDMARCA);

-- Llaves primarias para la tabla DETALLES_FACTURA
ALTER TABLE DETALLES_FACTURA ADD CONSTRAINT PK_DETALLESFACTURA PRIMARY KEY (IDDETALLEFACTURA);

-- Llaves primarias para la tabla FACTURAS_MAESTRAS
ALTER TABLE FACTURAS_MAESTRAS ADD CONSTRAINT PK_FACTURASMAESTRAS PRIMARY KEY (IDFACTURAMAESTRA);

-- Llaves primarias para la tabla DETALLES_SUMINISTRO
ALTER TABLE DETALLES_SUMINISTRO ADD CONSTRAINT PK_DETALLESSUMINISTRO PRIMARY KEY (IDDETALLESUMINISTRO);

-- Llaves primarias para la tabla SUMINISTROS_MAESTROS
ALTER TABLE SUMINISTROS_MAESTROS ADD CONSTRAINT PK_SUMINISTROSMAESTROS PRIMARY KEY (IDSUMINISTROMAESTRO);