CREATE TABLE ROLES_USUARIO (
    IDROLUSUARIO NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL,
    ESTADO NUMBER(1) NOT NULL CHECK (ESTADO IN (0, 1))
);

CREATE TABLE MODULOS_ACCESO (
    IDMODULOACCESO NUMBER NOT NULL,
    IDROLUSUARIO NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL,
    ESTADO NUMBER(1) NOT NULL CHECK (ESTADO IN (0, 1))
);

CREATE TABLE TIPOS_DOCUMENTO (
    IDTIPODOCUMENTO NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE USUARIOS (
    IDUSUARIO NUMBER NOT NULL,
    IDTIPODOCUMENTO NUMBER NOT NULL,
    IDROLUSUARIO NUMBER NOT NULL,
    PRIMERNOMBRE VARCHAR2(15) NOT NULL,
    SEGUNDONOMBRE VARCHAR2(15),
    PRIMERAPELLIDO VARCHAR2(15) NOT NULL,
    SEGUNDOAPELLIDO VARCHAR2(15),
    NUMERODOCUMENTO VARCHAR2(15) NOT NULL,
    CORREOELECTRONICO VARCHAR2(50),
    TELEFONO VARCHAR2(10),
    CELULAR VARCHAR2(10),
    NOMBREUSUARIO VARCHAR2(50) NOT NULL,
    CONTRASENA VARCHAR(255) NOT NULL,
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL,
    ESTADO NUMBER(1) NOT NULL CHECK (ESTADO IN (0, 1))
);

CREATE TABLE CLIENTES (
    IDCLIENTE NUMBER NOT NULL,
    IDTIPODOCUMENTO NUMBER NOT NULL,
    PRIMERNOMBRE VARCHAR2(15) NOT NULL,
    SEGUNDONOMBRE VARCHAR2(15),
    PRIMERAPELLIDO VARCHAR2(15) NOT NULL,
    SEGUNDOAPELLIDO VARCHAR2(15),
    NUMERODOCUMENTO VARCHAR2(15) NOT NULL,
    CORREOELECTRONICO VARCHAR2(50),
    TELEFONO VARCHAR2(10),
    CELULAR VARCHAR2(10),
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL,
    ESTADO NUMBER(1) NOT NULL CHECK (ESTADO IN (0, 1))
);

CREATE TABLE PROVEEDORES (
    IDPROVEEDOR NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    NUMERODOCUMENTO VARCHAR2(15) NOT NULL,
    CORREOELECTRONICO VARCHAR2(50),
    TELEFONO VARCHAR2(10),
    CELULAR VARCHAR2(10),
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL,
    ESTADO NUMBER(1) NOT NULL CHECK (ESTADO IN (0, 1))
);

CREATE TABLE CATEGORIAS_PRODUCTO (
    IDCATEGORIAPRODUCTO NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL,
    ESTADO NUMBER(1) NOT NULL CHECK (ESTADO IN (0, 1))
);

CREATE TABLE MARCAS (
    IDMARCA NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL,
    ESTADO NUMBER(1) NOT NULL CHECK (ESTADO IN (0, 1))
);

CREATE TABLE PRODUCTOS (
    IDPRODUCTO NUMBER NOT NULL,
    IDCATEGORIAPRODUCTO NUMBER NOT NULL,
    IDMARCA NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    PRECIOCOMPRA NUMBER(10, 2) NOT NULL,
    PRECIOVENTA NUMBER(10, 2) NOT NULL,
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL,
    ESTADO NUMBER(1) NOT NULL CHECK (ESTADO IN (0, 1))
);

CREATE TABLE FACTURAS_MAESTRAS (
    IDFACTURAMAESTRA NUMBER NOT NULL,
    IDUSUARIO NUMBER NOT NULL,
    IDCLIENTE NUMBER NOT NULL,
    MONTOPAGADO NUMBER(10, 2) NOT NULL,
    MONTOCAMBIO NUMBER(10, 2) NOT NULL,
    MONTOTOTAL NUMBER(10, 2) NOT NULL,
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE DETALLES_FACTURA (
    IDDETALLEFACTURA NUMBER NOT NULL,
    IDFACTURAMAESTRA NUMBER NOT NULL,
    IDPRODUCTO NUMBER NOT NULL,
    PRECIOVENTA NUMBER(10, 2) NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    MONTOTOTAL NUMBER(10, 2) NOT NULL
);

CREATE TABLE SUMINISTROS_MAESTROS (
    IDSUMINISTROMAESTRO NUMBER NOT NULL,
    IDUSUARIO NUMBER NOT NULL,
    IDPROVEEDOR NUMBER NOT NULL,
    MONTOTOTAL NUMBER(10, 2) NOT NULL,
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE DETALLES_SUMINISTRO (
    IDDETALLESUMINISTRO NUMBER NOT NULL,
    IDSUMINISTROMAESTRO NUMBER NOT NULL,
    PRECIOCOMPRA NUMBER(10, 2) NOT NULL,
    PRECIOVENTA NUMBER(10, 2) NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    MONTOTOTAL NUMBER(10, 2) NOT NULL,
    IDPRODUCTO INT NOT NULL
);