-- Tablas
CREATE TABLE ROLES_USUARIO (
    IDROLUSUARIO NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL,
    ESTADO NUMBER(1) NOT NULL CHECK (ESTADO IN (0, 1))
);

CREATE TABLE MODULOS_ACCESO (
    IDMODULOACCESO NUMBER NOT NULL,
    IDROLUSUARIO NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL,
    ESTADO NUMBER(1) NOT NULL CHECK (ESTADO IN (0, 1))
);

CREATE TABLE TIPOS_DOCUMENTO (
    IDTIPODOCUMENTO NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE USUARIOS (
    IDUSUARIO NUMBER NOT NULL,
    IDTIPODOCUMENTO NUMBER NOT NULL,
    IDROLUSUARIO NUMBER NOT NULL,
    PRIMERNOMBRE VARCHAR2(15) NOT NULL,
    SEGUNDONOMBRE VARCHAR2(15),
    PRIMERAPELLIDO VARCHAR2(15) NOT NULL,
    SEGUNDOAPELLIDO VARCHAR2(15),
    NUMERODOCUMENTO VARCHAR2(15) NOT NULL,
    CORREOELECTRONICO VARCHAR2(50),
    TELEFONO VARCHAR2(10),
    CELULAR VARCHAR2(10),
    NOMBREUSUARIO VARCHAR2(50) NOT NULL,
    CONTRASENA VARCHAR(255) NOT NULL,
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL,
    ESTADO NUMBER(1) NOT NULL CHECK (ESTADO IN (0, 1))
);

CREATE TABLE CLIENTES (
    IDCLIENTE NUMBER NOT NULL,
    IDTIPODOCUMENTO NUMBER NOT NULL,
    PRIMERNOMBRE VARCHAR2(15) NOT NULL,
    SEGUNDONOMBRE VARCHAR2(15),
    PRIMERAPELLIDO VARCHAR2(15) NOT NULL,
    SEGUNDOAPELLIDO VARCHAR2(15),
    NUMERODOCUMENTO VARCHAR2(15) NOT NULL,
    CORREOELECTRONICO VARCHAR2(50),
    TELEFONO VARCHAR2(10),
    CELULAR VARCHAR2(10),
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL,
    ESTADO NUMBER(1) NOT NULL CHECK (ESTADO IN (0, 1))
);

CREATE TABLE PROVEEDORES (
    IDPROVEEDOR NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    NUMERODOCUMENTO VARCHAR2(15) NOT NULL,
    CORREOELECTRONICO VARCHAR2(50),
    TELEFONO VARCHAR2(10),
    CELULAR VARCHAR2(10),
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL,
    ESTADO NUMBER(1) NOT NULL CHECK (ESTADO IN (0, 1))
);

CREATE TABLE CATEGORIAS_PRODUCTO (
    IDCATEGORIAPRODUCTO NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL,
    ESTADO NUMBER(1) NOT NULL CHECK (ESTADO IN (0, 1))
);

CREATE TABLE MARCAS (
    IDMARCA NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL,
    ESTADO NUMBER(1) NOT NULL CHECK (ESTADO IN (0, 1))
);

CREATE TABLE PRODUCTOS (
    IDPRODUCTO NUMBER NOT NULL,
    IDCATEGORIAPRODUCTO NUMBER NOT NULL,
    IDMARCA NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    PRECIOCOMPRA NUMBER(10, 2) NOT NULL,
    PRECIOVENTA NUMBER(10, 2) NOT NULL,
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL,
    ESTADO NUMBER(1) NOT NULL CHECK (ESTADO IN (0, 1))
);

CREATE TABLE FACTURAS_MAESTRAS (
    IDFACTURAMAESTRA NUMBER NOT NULL,
    IDUSUARIO NUMBER NOT NULL,
    IDCLIENTE NUMBER NOT NULL,
    MONTOPAGADO NUMBER(10, 2) NOT NULL,
    MONTOCAMBIO NUMBER(10, 2) NOT NULL,
    MONTOTOTAL NUMBER(10, 2) NOT NULL,
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE DETALLES_FACTURA (
    IDDETALLEFACTURA NUMBER NOT NULL,
    IDFACTURAMAESTRA NUMBER NOT NULL,
    IDPRODUCTO NUMBER NOT NULL,
    PRECIOVENTA NUMBER(10, 2) NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    MONTOTOTAL NUMBER(10, 2) NOT NULL
);

CREATE TABLE SUMINISTROS_MAESTROS (
    IDSUMINISTROMAESTRO NUMBER NOT NULL,
    IDUSUARIO NUMBER NOT NULL,
    IDPROVEEDOR NUMBER NOT NULL,
    MONTOTOTAL NUMBER(10, 2) NOT NULL,
    FECHACREACION DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE DETALLES_SUMINISTRO (
    IDDETALLESUMINISTRO NUMBER NOT NULL,
    IDSUMINISTROMAESTRO NUMBER NOT NULL,
    PRECIOCOMPRA NUMBER(10, 2) NOT NULL,
    PRECIOVENTA NUMBER(10, 2) NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    MONTOTOTAL NUMBER(10, 2) NOT NULL,
    IDPRODUCTO INT NOT NULL
);

-- Llaves primarias
ALTER TABLE MODULOS_ACCESO ADD CONSTRAINT PK_MODULOSACCESO PRIMARY KEY (IDMODULOACCESO);

ALTER TABLE ROLES_USUARIO ADD CONSTRAINT PK_ROLESUSUARIO PRIMARY KEY (IDROLUSUARIO);

ALTER TABLE TIPOS_DOCUMENTO ADD CONSTRAINT PK_TIPOSDOCUMENTO PRIMARY KEY (IDTIPODOCUMENTO);

ALTER TABLE USUARIOS ADD CONSTRAINT PK_USUARIOS PRIMARY KEY (IDUSUARIO);

ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY (IDCLIENTE);

ALTER TABLE PROVEEDORES ADD CONSTRAINT PK_PROVEEDORES PRIMARY KEY (IDPROVEEDOR);

ALTER TABLE CATEGORIAS_PRODUCTO ADD CONSTRAINT PK_CATEGORIAPRODUCTO PRIMARY KEY (IDCATEGORIAPRODUCTO);

ALTER TABLE PRODUCTOS ADD CONSTRAINT PK_PRODUCTOS PRIMARY KEY (IDPRODUCTO);

ALTER TABLE MARCAS ADD CONSTRAINT PK_MARCAS PRIMARY KEY (IDMARCA);

ALTER TABLE DETALLES_FACTURA ADD CONSTRAINT PK_DETALLESFACTURA PRIMARY KEY (IDDETALLEFACTURA);

ALTER TABLE FACTURAS_MAESTRAS ADD CONSTRAINT PK_FACTURASMAESTRAS PRIMARY KEY (IDFACTURAMAESTRA);

ALTER TABLE DETALLES_SUMINISTRO ADD CONSTRAINT PK_DETALLESSUMINISTRO PRIMARY KEY (IDDETALLESUMINISTRO);

ALTER TABLE SUMINISTROS_MAESTROS ADD CONSTRAINT PK_SUMINISTROSMAESTROS PRIMARY KEY (IDSUMINISTROMAESTRO);

-- Llaves foraneas
ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_TIPOSDOCUMENTO FOREIGN KEY (IDTIPODOCUMENTO) REFERENCES TIPOS_DOCUMENTO (IDTIPODOCUMENTO);

ALTER TABLE CLIENTES ADD CONSTRAINT FK_CLIENTES_TIPOSDOCUMENTO FOREIGN KEY (IDTIPODOCUMENTO) REFERENCES TIPOS_DOCUMENTO (IDTIPODOCUMENTO);

ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_ROLESUSUARIO FOREIGN KEY (IDROLUSUARIO) REFERENCES ROLES_USUARIO (IDROLUSUARIO);

ALTER TABLE MODULOS_ACCESO ADD CONSTRAINT FK_MODULOSACCESO_ROLESUSUARIO FOREIGN KEY (IDROLUSUARIO) REFERENCES ROLES_USUARIO (IDROLUSUARIO);

ALTER TABLE PRODUCTOS ADD CONSTRAINT FK_PRODUCTOS_CATEGORIASPRODUCTO FOREIGN KEY (IDCATEGORIAPRODUCTO) REFERENCES CATEGORIAS_PRODUCTO (IDCATEGORIAPRODUCTO);

ALTER TABLE PRODUCTOS ADD CONSTRAINT FK_PRODUCTOS_MARCAS FOREIGN KEY (IDMARCA) REFERENCES MARCAS (IDMARCA);

ALTER TABLE FACTURAS_MAESTRAS ADD CONSTRAINT FK_FACTURASMAESTRAS_USUARIOS FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS (IDUSUARIO);

ALTER TABLE SUMINISTROS_MAESTROS ADD CONSTRAINT FK_SUMINISTROS_MAESTROS_USUARIOS FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS (IDUSUARIO);

ALTER TABLE FACTURAS_MAESTRAS ADD CONSTRAINT FK_FACTURASMAESTRAS_CLIENTES FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTES (IDCLIENTE);

ALTER TABLE SUMINISTROS_MAESTROS ADD CONSTRAINT FK_FACTURASMAESTRAS_PROVEEDORES FOREIGN KEY (IDPROVEEDOR) REFERENCES PROVEEDORES (IDPROVEEDOR);

ALTER TABLE DETALLES_FACTURA ADD CONSTRAINT FK_DETALLESFACTURA_PRODUCTOS FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTOS (IDPRODUCTO);

ALTER TABLE DETALLES_SUMINISTRO ADD CONSTRAINT FK_DETALLESSUMINISTRO_PRODUCTOS FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTOS (IDPRODUCTO);

ALTER TABLE DETALLES_FACTURA ADD CONSTRAINT FK_DETALLESFACTURA_FACTURASMAESTRAS FOREIGN KEY (IDFACTURAMAESTRA) REFERENCES FACTURAS_MAESTRAS (IDFACTURAMAESTRA);

ALTER TABLE DETALLES_SUMINISTRO ADD CONSTRAINT FK_DETALLESSUMINISTRO_SUMINISTROSMAESTROS FOREIGN KEY (IDSUMINISTROMAESTRO) REFERENCES SUMINISTROS_MAESTROS (IDSUMINISTROMAESTRO);

-- Atributos unicos 
ALTER TABLE CLIENTES ADD CONSTRAINT UC_CLIENTES_CORREOELECTRONICO UNIQUE (CORREOELECTRONICO);

ALTER TABLE CLIENTES ADD CONSTRAINT UC_CLIENTES_NUMERODOCUMENTO UNIQUE (NUMERODOCUMENTO);

ALTER TABLE USUARIOS ADD CONSTRAINT UC_USUARIOS_CORREOELECTRONICO UNIQUE (CORREOELECTRONICO);

ALTER TABLE USUARIOS ADD CONSTRAINT UC_USUARIOS_NUMERODOCUMENTO UNIQUE (NUMERODOCUMENTO);

ALTER TABLE PROVEEDORES ADD CONSTRAINT UC_PROVEEDORES_CORREOELECTRONICO UNIQUE (CORREOELECTRONICO);

ALTER TABLE PROVEEDORES ADD CONSTRAINT UC_PROVEEDORES_NUMERODOCUMENTO UNIQUE (NUMERODOCUMENTO);